version: '3.4'

services:
  identityandjwt.api2:
    image: ${DOCKER_REGISTRY-}identityandjwtapi2
    build:
      context: .
      dockerfile: IdentityandJwt.Api2/Dockerfile

  identityandjwtapi:
    image: ${DOCKER_REGISTRY-}identityandjwtapi
    build:
      context: .
      dockerfile: IdentityandJwtApi/Dockerfile
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1536m -Xmx1536m
      - xpack.security.enabled=false
          
    ulimits:
       memlock:
            soft: -1
            hard: -1
       nofile:
            soft: 65536
            hard: 65536
    ports:
          - 9200:9200
          - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.3
    environment:
     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
          - "5601:5601"
  ##kibana:
  ##  image: docker.elasticsearch.co/kibana/kibana:6.5.3
  ##  environment:
  ##    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  ##  ports:
  ##   - 5601:5601  


