version: '3.4'

services:
  identityandjwt.api2:
    image: identityandjwtapi2:dev
    container_name: IdentityandJwt.Api2
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "IdentityandJwt.Api2"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_identityandjwt.api2$
    volumes:
      - D:\VisualStudioProjeler\IdentityandJwt\IdentityandJwt.Api2:/app
      - D:\VisualStudioProjeler\IdentityandJwt:/src
      - C:\Users\Zehra.Karahan\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_identityandjwt.api2$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_identityandjwt.api2$ \"/app/bin/Debug/netcoreapp3.1/IdentityandJwt.Api2.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  identityandjwtapi:
    image: identityandjwtapi:dev
    container_name: IdentityandJwtApi
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "IdentityandJwtApi"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_identityandjwtapi$
    volumes:
      - D:\VisualStudioProjeler\IdentityandJwt\IdentityandJwtApi:/app
      - D:\VisualStudioProjeler\IdentityandJwt:/src
      - C:\Users\Zehra.Karahan\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_identityandjwtapi$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_identityandjwtapi$ \"/app/bin/Debug/netcoreapp3.1/IdentityandJwtApi.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
